"""Round-trip and mask correctness for :class:`ActionEncoder`.

Property: for every reachable state, every action in ``legal_actions`` either
- round-trips through ``decode(encode(a), state) == a`` (strict equality), or
- belongs to a known equivalence class explicitly handled below
  (year-of-plenty: unordered pair; discard: collapsed to the sentinel
  trigger; domestic trade: not in the layout, encoder raises ``ValueError``).

State coverage is generated by random rollouts, which is the closest the
project has to a stationary distribution over reachable positions; 50 seeds ×
100 steps ≈ 5 000 visited states.
"""

from __future__ import annotations

import random

import numpy as np
import pytest
from hypothesis import given, settings, strategies as st

from domain.actions import all_actions as A
from domain.actions.base import Action
from domain.engine.game_engine import IllegalActionError
from domain.enums import Resource, TurnPhase
from domain.game.state import GameState
from rl.encoding._action_layout import (
    _ACTION_LAYOUT_VERSION,
    ACTION_SPACE_SIZE,
    DISCARD_INDEX,
    MARITIME_TRADE_PAIRS,
    MARITIME_TRADE_START,
    N_MARITIME_TRADES,
    N_YEAR_OF_PLENTY,
    ROLL_INDEX,
    YOP_PAIRS,
)
from rl.encoding.action import ActionEncoder, DiscardSentinel
from rl.env.catan_env import CatanEnv


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Domestic-trade actions are not in the layout (rl-005); the encoder raises
# ValueError for them. The property test filters them out before the
# round-trip check.
_DOMESTIC_TRADE_TYPES: tuple[type, ...] = (
    A.ProposeDomesticTradeAction,
    A.RespondDomesticTradeAction,
    A.ConfirmDomesticTradeAction,
    A.CancelDomesticTradeAction,
)


def _yop_unordered(a: A.PlayYearOfPlentyAction) -> frozenset[Resource]:
    return frozenset((a.resource1, a.resource2)) if a.resource1 is not a.resource2 else frozenset({a.resource1})


def _actions_equivalent(a: Action, b: Action) -> bool:
    """Equality up to known semantic-equivalence classes.

    PlayYearOfPlentyAction is order-insensitive in (resource1, resource2);
    the encoder canonicalises to sorted-by-enum form during decode, so
    ``PlayYOP(WOOD, BRICK)`` may round-trip as ``PlayYOP(BRICK, WOOD)``
    (engine emits both orderings).
    """
    if isinstance(a, A.PlayYearOfPlentyAction) and isinstance(
        b, A.PlayYearOfPlentyAction
    ):
        if a.player_id != b.player_id:
            return False
        return _yop_unordered(a) == _yop_unordered(b)
    return a == b


def _rollout_states(seed: int, max_steps: int) -> list[GameState]:
    """Drive ``CatanEnv`` with uniform-random legal moves and snapshot states.

    Yields ``max_steps + 1`` states (initial plus one per applied action), or
    fewer if the game terminates earlier.
    """
    env = CatanEnv(seed=seed)
    env.reset(seed=seed)
    rng = random.Random(seed)
    states: list[GameState] = [env.state]
    for _ in range(max_steps):
        legal = env.legal_actions()
        if not legal:
            break
        action = rng.choice(legal)
        _obs, _r, done, _info = env.step(action)
        states.append(env.state)
        if done:
            break
    return states


# ---------------------------------------------------------------------------
# Static layout sanity
# ---------------------------------------------------------------------------


def test_action_layout_version_pinned() -> None:
    assert _ACTION_LAYOUT_VERSION == 1


def test_action_space_size_matches_layout_table() -> None:
    # Sum of widths in the layout table.
    expected = (
        72  # roads
        + 54  # settlements
        + 54  # cities
        + 19  # robber moves
        + 4   # steal seats
        + 20  # maritime trades
        + 1   # roll
        + 1   # end turn
        + 1   # buy dev
        + 2   # knight + road building
        + 5   # monopoly
        + 15  # year of plenty
        + 1   # discard trigger
    )
    assert ACTION_SPACE_SIZE == expected
    assert ACTION_SPACE_SIZE == 249


def test_maritime_trade_pairs_have_no_self_trades() -> None:
    assert len(MARITIME_TRADE_PAIRS) == N_MARITIME_TRADES == 20
    for give, receive in MARITIME_TRADE_PAIRS:
        assert give is not receive


def test_year_of_plenty_pairs_are_unordered_and_unique() -> None:
    assert len(YOP_PAIRS) == N_YEAR_OF_PLENTY == 15
    seen_unordered: set[frozenset[Resource]] = set()
    for r1, r2 in YOP_PAIRS:
        key = frozenset({r1, r2}) if r1 is not r2 else frozenset({r1})
        assert key not in seen_unordered, f"duplicate unordered pair {(r1, r2)}"
        seen_unordered.add(key)


# ---------------------------------------------------------------------------
# Decoding bounds and unhappy paths
# ---------------------------------------------------------------------------


def test_decode_out_of_range_raises() -> None:
    env = CatanEnv(seed=0)
    enc = ActionEncoder.for_state(env.state)
    with pytest.raises(ValueError):
        enc.decode(-1, env.state)
    with pytest.raises(ValueError):
        enc.decode(ACTION_SPACE_SIZE, env.state)


def test_encode_unsupported_action_raises() -> None:
    enc = ActionEncoder([])
    fake = A.ProposeDomesticTradeAction(
        player_id=0,  # type: ignore[arg-type]
        offer={},
        request={},
    )
    with pytest.raises(ValueError):
        enc.encode(fake)


# ---------------------------------------------------------------------------
# Property tests via random rollouts
# ---------------------------------------------------------------------------


@settings(max_examples=50, deadline=None)
@given(st.integers(min_value=0, max_value=10_000))
def test_round_trip_over_reachable_states(seed: int) -> None:
    states = _rollout_states(seed, max_steps=120)
    for state in states:
        enc = ActionEncoder.for_state(state)
        for action in _legal_actions(state):
            if isinstance(action, _DOMESTIC_TRADE_TYPES):
                continue  # not in layout; encoder raises by design
            idx = enc.encode(action)
            assert 0 <= idx < ACTION_SPACE_SIZE

            decoded = enc.decode(idx, state)

            if isinstance(action, A.DiscardResourcesAction):
                # Combinatorial payload is collapsed to the sentinel.
                assert idx == DISCARD_INDEX
                assert isinstance(decoded, DiscardSentinel)
                assert decoded.player_id == action.player_id
                continue

            assert _actions_equivalent(decoded, action), (
                f"round-trip failed: {action!r} -> {idx} -> {decoded!r}"
            )


@settings(max_examples=30, deadline=None)
@given(st.integers(min_value=0, max_value=10_000))
def test_mask_cardinality_matches_distinct_encoded_indices(seed: int) -> None:
    states = _rollout_states(seed, max_steps=60)
    for state in states:
        enc = ActionEncoder.for_state(state)
        legal = _legal_actions(state)
        encodable = [a for a in legal if not isinstance(a, _DOMESTIC_TRADE_TYPES)]
        m = enc.mask(legal)
        assert m.shape == (ACTION_SPACE_SIZE,)
        assert m.dtype == np.bool_
        expected = {enc.encode(a) for a in encodable}
        assert int(m.sum()) == len(expected)
        for idx in expected:
            assert m[idx]


@settings(max_examples=20, deadline=None)
@given(st.integers(min_value=0, max_value=10_000))
def test_decoded_index_outside_mask_is_rejected_by_engine(seed: int) -> None:
    """An index whose mask bit is False decodes to an action the engine refuses.

    Excludes the discard sentinel (not an Action) and indices that decode to
    something whose engine validation raises a TypeError or KeyError before
    the legality check (none currently, but worth pinning).
    """
    from domain.engine.game_engine import GameEngine
    from domain.engine.randomizer import SeededRandomizer

    states = _rollout_states(seed, max_steps=40)
    rng = random.Random(seed)
    for state in states:
        enc = ActionEncoder.for_state(state)
        m = enc.mask(_legal_actions(state))
        false_indices = [i for i in range(ACTION_SPACE_SIZE) if not m[i] and i != DISCARD_INDEX]
        if not false_indices:
            continue
        # Sample a handful per state — exhaustive scan would be slow.
        for idx in rng.sample(false_indices, k=min(8, len(false_indices))):
            try:
                decoded = enc.decode(idx, state)
            except ValueError:
                # Out-of-range steal seats etc. — fine; never reach engine.
                continue
            if isinstance(decoded, DiscardSentinel):
                continue
            engine = GameEngine(SeededRandomizer(seed))
            with pytest.raises(IllegalActionError):
                engine.apply_action(state, decoded)


# ---------------------------------------------------------------------------
# Targeted edge cases
# ---------------------------------------------------------------------------


def test_road_decode_phase_dependent() -> None:
    """Setup phases decode road indices to PlaceRoadAction; main phases to BuildRoadAction."""
    env = CatanEnv(seed=0)
    env.reset(seed=0)
    enc = ActionEncoder.for_state(env.state)

    # Drive to a state in INITIAL_ROAD by stepping the first legal action.
    while env.state.phase is not TurnPhase.INITIAL_ROAD:
        env.step(env.legal_actions()[0])
        if env.state.phase is TurnPhase.INITIAL_SETTLEMENT:
            continue

    decoded = enc.decode(0, env.state)
    assert isinstance(decoded, A.PlaceRoadAction)

    # Walk past setup into a non-setup phase.
    while env.state.phase in (TurnPhase.INITIAL_SETTLEMENT, TurnPhase.INITIAL_ROAD):
        env.step(env.legal_actions()[0])
    decoded = enc.decode(0, env.state)
    assert isinstance(decoded, A.BuildRoadAction)


def test_maritime_indices_have_distinct_resources() -> None:
    """All 20 maritime indices decode with give != receive."""
    env = CatanEnv(seed=0)
    enc = ActionEncoder.for_state(env.state)
    for offset in range(N_MARITIME_TRADES):
        idx = MARITIME_TRADE_START + offset
        # Decode requires we be in a state where the action class is well-defined;
        # decoding doesn't depend on phase for maritime, so use the fresh state.
        decoded = enc.decode(idx, env.state)
        assert isinstance(decoded, A.MaritimeTradeAction)
        assert decoded.give is not decoded.receive


def test_roll_index_decodes_to_roll_dice() -> None:
    env = CatanEnv(seed=0)
    enc = ActionEncoder.for_state(env.state)
    decoded = enc.decode(ROLL_INDEX, env.state)
    assert isinstance(decoded, A.RollDiceAction)


def _legal_actions(state: GameState) -> list[Action]:
    from domain.engine.game_engine import GameEngine
    from domain.engine.randomizer import SeededRandomizer

    return GameEngine(SeededRandomizer(0)).legal_actions(state)
